version: '3.8'

services:
  app:
    image: golang:1.23
    container_name: go_dev
    working_dir: /app
    volumes:
      - .:/app  # カレントディレクトリをコンテナ内の /app にマウント
    ports:
      - "8087:8080"  # API サーバー用のポート（必要なら変更）
    environment:
      - GO111MODULE=on
      - GOPROXY=https://proxy.golang.org,direct
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcloud-key.json
    env_file:
      - .env
    stdin_open: true
    tty: true