apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: my-backend-config
spec:
  connectionDraining:
    drainingTimeoutSec: 30
  timeoutSec: 60
  healthCheck:
    type: HTTP
    requestPath: /healthz
