apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: asia-northeast1-docker.pkg.dev/hunger-gourmet/streaming-server/app:latest
          ports:
            - containerPort: 8080