apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  annotations:
    cloud.google.com/load-balancer-type: "External"
    cloud.google.com/neg: '{"exposed_ports": {"80":{"backend_config":"my-backend-config"}}}'
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local  # 必ず同じ Pod に接続
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  sessionAffinity: ClientIP  # クライアントの IP に応じて特定の Pod にルーティング
